# Generated by Django 4.2.17 on 2025-01-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCard',
        ),
    ]
