# Generated by Django 4.2.17 on 2025-01-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_delete_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
