# Generated by Django 4.2.17 on 2025-01-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='concern',
            field=models.TextField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.TextField(max_length=500),
        ),
    ]
