# Generated by Django 4.2.17 on 2025-01-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_concern_alter_vehicle_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tasks',
            field=models.JSONField(default=list),
        ),
    ]
