# Generated by Django 4.2.17 on 2025-01-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tasks',
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='vehicles.vehicle')),
            ],
        ),
    ]
