# Generated by Django 4.2.16 on 2024-12-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customerprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('service_adviser', 'Service Adviser')], default='customer', max_length=20),
        ),
    ]
