# Generated by Django 4.2.17 on 2025-01-15 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='service_adviser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sa_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
